# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demo_workspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: default_resourse_group
  aml_workspace: demo_workspace
  application_insights: demoworkspace1997734687
  key_vault: demoworkspace9715646723
  container_registry: a9c528dba4cc4042a824b912e74ef850
  storage_account: demoworkspace0813584800
  
  # # For terraform reference
  # terraform_version: 0.14.7
  # terraform_workingdir: infrastructure
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_location: $(location)
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab
