# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: FitwellWorkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: default_resource_group
  aml_workspace: FitwellWorkspace
  application_insights: fitwellworkspa9912283553
  key_vault: fitwellworkspa7534202814
  container_registry: af5a175d168046d4bd483fe8ca126196
  storage_account: fitwellworkspa6664757551
  
  # # For terraform reference
  # terraform_version: 0.14.7
  # terraform_workingdir: infrastructure
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_location: $(location)
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab



